name: Update Contributors

on:
  schedule:
    - cron: "0 0 * * 0" # chạy mỗi tuần 1 lần (Chủ nhật 0h)
  workflow_dispatch: # có thể bấm tay chạy trong Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Update Contributors
        run: npm run contrib

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: update contributors [skip ci]" || echo "No changes to commit"
          git push
